[package]
name = "tl"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "tl"
path = "source/main.rs"


[lib]
name = "tl"
path = "source/lib.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
